word_data = {
    "Cuckoo": ("布穀鳥; 瘋狂的; 愚蠢的", "He's acting totally cuckoo!"),
    "Dope": ("毒品; 很酷的; 傻瓜", "Don't be a dope, read the instructions first!"),
    "Zoology": ("動物學", "She is studying zoology at the university."),
    "Botany": ("植物學", "Botany is essential for understanding plant life."),
    "Patent": ("專利", "He filed a patent for his new invention."),
    "File": ("提交; 申請（法律、官方文件）", "She filed a complaint against the company."),
    "Cotton gin": ("軋棉機，一種用來分離棉花纖維與種子的機械", "Eli Whitney invented the cotton gin in 1793."),
    "Circumference": ("圓周，圓的外圍長度", "The circumference of the Earth is approximately 40,075 kilometers."),
    "Diameter": ("直徑，通過圓心的兩點之間的距離", "The diameter of the basketball hoop is 18 inches."),
    "Radius": ("半徑，從圓心到圓周的距離", "To find the area of a circle, you need to square the radius and multiply by π."),
    "Bowling ball": ("保齡球", "He rolled the bowling ball down the lane and scored a strike."),
    "Blockheaded": ("笨蛋的; 愚蠢的", "Stop being so blockheaded and listen to the instructions!"),
    "Varicose vein": ("靜脈曲張", "She had to see a doctor about her varicose veins."),
    "Blast off": ("發射; 起飛", "The rocket will blast off at dawn."),
    "Relativity": ("相對論; 相關性", "Einstein's theory of relativity changed the way we understand space and time."),
    "Bar code": ("條形碼", "The cashier scanned the bar code to check the price of the item."),
    "Fiber optic": ("光纖的", "Fiber optic cables enable high-speed internet connections."),
    "Doritos": ("多力多滋（玉米片品牌）", "She grabbed a bag of Doritos for a quick snack."),
    "Equator": ("赤道", "The equator divides the Earth into the Northern and Southern Hemispheres."),
    "Encircle": ("環繞; 圍繞", "The army encircled the enemy's camp to cut off their escape."),
    "Jell-o": ("果凍（品牌名稱，常指明膠甜點）", "The kids love eating strawberry Jell-O for dessert."),
    "Crackpot": ("瘋子; 怪人", "He came up with another crackpot conspiracy theory."),
    "Nutty": ("瘋狂的; 古怪的; 含堅果的", "That’s a nutty idea, but it just might work!"),
    "Hound": ("獵犬; 追逼; 纏著某人", "The paparazzi continued to hound the celebrity for a statement."),
    "Beam me up": ("傳送我上去（來自《星際迷航》）", "Scotty, beam me up! There's nothing left for us here."),
    "Endorse": ("支持; 背書; 推薦", "The famous athlete was paid to endorse the new brand of running shoes."),
    "Scatterbrain": ("健忘的人; 注意力不集中的人", "She’s such a scatterbrain—she always forgets her keys!"),
    "Scatterbrained": ("健忘的; 注意力不集中的", "I’ve been so scatterbrained lately that I left my phone in the fridge!"),
    "Engross": ("使全神貫注; 使專心", "The thrilling novel engrossed him so much that he lost track of time."),
    "Engrossed": ("全神貫注的; 專心的", "She was so engrossed in the movie that she didn’t hear her phone ring."),
    "Deflect": ("使偏斜; 轉移; 避開", "He used his shield to deflect the incoming attack."),
    "Rheumatism": ("風濕病", "His grandmother suffers from rheumatism and finds it hard to move in cold weather."),
    "Orchid": ("蘭花", "She received a beautiful orchid as a gift for her birthday."),
    "Hydraulic": ("液壓的; 水力的", "The mechanic repaired the hydraulic system of the excavator."),
    "On-and-off": ("斷斷續續的; 時好時壞的", "Their relationship has been on-and-off for years."),
    "Serenade": ("為…演奏或演唱小夜曲", "He serenaded her with a beautiful love song under her balcony."),
    "Fudge": ("軟糖; 含糊其詞; 捏造", "She made delicious chocolate fudge for dessert."),
    "Mortified": ("感到羞愧的; 窘迫的", "She was mortified when she tripped on stage during her speech."),
    "Darnedest": ("極端的; 非常奇怪的或令人驚訝的", "He tried his darnedest to win the race but came in second."),
    "Artery": ("動脈; 主要道路", "The doctor explained that a blocked artery can lead to a heart attack."),
    "Cremate": ("火化; 焚化", "The family decided to cremate their loved one according to his wishes."),
    "Autopsy": ("驗屍; 屍檢", "The autopsy revealed the cause of death was natural."),
    "Picnic cooler": ("野餐冷藏箱", "They packed sandwiches and drinks in the picnic cooler for their trip."),
    "Duffel bag": ("圓筒形帆布袋; 行李袋", "He packed all his clothes into a duffel bag before heading to the airport."),
    "String bean": ("四季豆; 瘦高的人", "He’s so tall and thin—he looks like a string bean!"),
    "Celery punch": ("芹菜調製飲料（可能指一種混合芹菜汁的飲品）", "She made a refreshing celery punch with lemon and ginger."),
    "Convertible": ("敞篷車; 可轉換的", "He drove down the highway in his red convertible with the top down."),
}



